# Generated by Django 4.1.7 on 2023-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndn', models.CharField(max_length=10)),
                ('cikknev', models.CharField(max_length=200)),
            ],
        ),
    ]
